# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'caleb-instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for caleb-instagram

  pod 'Parse'
  pod 'Parse/UI'
  pod 'DateTools'
  target 'caleb-instagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'caleb-instagramUITests' do
    # Pods for testing
  end

end
